---
language: python
services: docker

env:
  global:
    - ROLE_NAME: fail2ban
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: fedora27

install:
  - pip install molecule docker ansible

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME hwwilliams.$ROLE_NAME
  - cd hwwilliams.$ROLE_NAME
  - ansible-galaxy install -r requirements.yml

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
