---
- name: Ensure Fail2Ban and Sendmail Are Present
  become: true
  package:
    name:
        - fail2ban
        - sendmail
    state: present

- name: Ensure Fail2Ban Sendmail Actions Is Present
  become: true
  yum:
    name: fail2ban-sendmail
    state: present
  when: ansible_os_family == 'RedHat'

- name: Include Fail2Ban Firewalld Related Tasks
  include_tasks:
    file: firewalld.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure Sendmail Is Running and Starts At Boot
  become: true
  systemd:
    name: sendmail
    state: started
    enabled: true

- name: Ensure Fail2Ban Is Running and Starts At Boot
  become: true
  systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Ensure Fail2Ban Local Jail Configuration File Is Present
  become: true
  template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: 0644
  notify: Restart Fail2Ban
